app/cf/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("shop.urls", namespace="shop")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/shop/urls.py
from django.urls import path

from . import views

app_name = "shop"

urlpatterns = [
    path("", views.product_list, name="product_list"),
    path("<slug:category_slug>/", views.product_list, name="product_list_by_category"),
    path(
        "<int:id>/<slug:slug>/",
        views.ProductDetailView.as_view(),
        name="product-detail",
    ),
]

app/shop/models.py
from django.db import models
from django.urls import reverse
from django.utils.text import slugify
from django_resized import ResizedImageField


class Category(models.Model):
    name = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200, unique=True)

    class Meta:
        ordering = ("name",)
        verbose_name = "category"
        verbose_name_plural = "categories"

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name)
        super(Category, self).save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse("shop:product_list_by_category", args=[self.slug])

    def __str__(self):
        return self.name


class Product(models.Model):
    category = models.ForeignKey(
        Category,
        related_name="products",
        on_delete=models.CASCADE,
        null=True,
        blank=True,
    )
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True)
    image = models.ImageField(upload_to='product_images', blank=True, null=True)
    details = models.TextField(blank=True)
    price = models.DecimalField(
        max_digits=10, decimal_places=2, blank=True, null=True, default=2
    )
    is_available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ("name",)
        index_together = (("id", "slug"),)

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name)
        super(Product, self).save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse("shop:product-detail", args=[self.id, self.slug])

    def __str__(self):
        return f"{self.name} ({self.price})"

app/users/models.py
from django.db import models

# Create your models here.

app/shop/views.py
from django.shortcuts import get_object_or_404, render
from django.views.generic import DetailView

from .models import Category, Product


def product_list(request, category_slug=None):
    category = None
    category_list = Category.objects.all()
    product_list = Product.objects.filter(is_available=True)
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        product_list = product_list.filter(category=category)
    return render(
        request,
        "shop/product_list.html",
        {
            "category": category,
            "category_list": category_list,
            "product_list": product_list,
        },
    )


class ProductDetailView(DetailView):
    model = Product
    # template_name = "shop/product_detail.html"

    # def get_context_data(self, **kwargs):
    #     context = super(ProductDetailView, self).get_context_data(**kwargs)
    #     context["related_products"] = Product.objects.filter(category=self.object.category).exclude(pk=self.object.pk)
    #     return context

app/users/views.py
from django.shortcuts import render

# Create your views here.

app/templates/base.html
<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport"
        content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link
        href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
        rel="stylesheet"
        integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3"
        crossorigin="anonymous">
    <link rel="preconnect"
        href="https://fonts.googleapis.com">
    <link rel="preconnect"
        href="https://fonts.gstatic.com"
        crossorigin>
    <link
        href="https://fonts.googleapis.com/css2?family=Montserrat&display=swap"
        rel="stylesheet">
    <style>
        html,
        body {
            font-family: 'Montserrat', sans-serif;
        }
    </style>

    <title>

        {% block head_title %}

        {% endblock head_title %}
        Tech-Cafe
    </title>
</head>

<body>
    {% include 'header.html' %}
    <div class="min-vh-100">

        {% block content %}

        {% endblock content %}
    </div>

    {% include 'footer.html' %}


    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script
        src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
        crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
    -->
</body>

</html>

app/templates/footer.html
<div class="container">
    <footer
        class="d-flex flex-wrap justify-content-between align-items-center py-3 my-4 border-top">
        <div class="col-md-4 d-flex align-items-center">
            <a href="/"
                class="mb-3 me-2 mb-md-0 text-muted text-decoration-none lh-1">
                <svg class="bi"
                    width="30"
                    height="24">
                    <use xlink:href="#bootstrap" />
                </svg>
            </a>
            <span class="text-muted">&copy; {% now "Y" %} <a class="text-decoration-none text-muted" target="_target" href="http://ksslu.com/">kingship</a></span>
        </div>

        <ul class="nav col-md-4 justify-content-end list-unstyled d-flex">
            <li class="ms-3"><a class="text-muted"
                    href="#"><svg class="bi"
                        width="24"
                        height="24">
                        <use xlink:href="#twitter" />
                    </svg></a></li>
            <li class="ms-3"><a class="text-muted"
                    href="#"><svg class="bi"
                        width="24"
                        height="24">
                        <use xlink:href="#instagram" />
                    </svg></a></li>
            <li class="ms-3"><a class="text-muted"
                    href="#"><svg class="bi"
                        width="24"
                        height="24">
                        <use xlink:href="#facebook" />
                    </svg></a></li>
        </ul>
    </footer>
</div>

app/templates/header.html
<header class="p-3 bg-dark text-white">
    <div class="container">
      <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
        <a href="/" class="d-flex align-items-center mb-2 mb-lg-0 text-white text-decoration-none">
          <svg class="bi me-2" width="40" height="32" role="img" aria-label="Bootstrap"><use xlink:href="#bootstrap"/></svg>
        </a>

        <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
          <li><a href="#" class="nav-link px-2 text-secondary">Home</a></li>
          <li><a href="#" class="nav-link px-2 text-white">Features</a></li>
          <li><a href="#" class="nav-link px-2 text-white">Pricing</a></li>
          <li><a href="#" class="nav-link px-2 text-white">FAQs</a></li>
          <li><a href="#" class="nav-link px-2 text-white">About</a></li>
        </ul>

        <form class="col-12 col-lg-auto mb-3 mb-lg-0 me-lg-3">
          <input type="search" class="form-control form-control-dark" placeholder="Search..." aria-label="Search">
        </form>

        <div class="text-end">
          <button type="button" class="btn btn-outline-light me-2">Login</button>
          <button type="button" class="btn btn-warning">Sign-up</button>
        </div>
      </div>
    </div>
  </header>

app/templates/shop/product_list.html
{% extends 'base.html' %}
{% load static %}


{% block head_title %}
{% if category %}{{ category.name|title }}{% else %}Products{% endif %} -
{% endblock head_title %}


{% block content %}
<div class="container">
    <div class="row">
        <div class="col-lg-3">
            <div style="border-radius:1rem;" class="border bg-light shadow p-4 mt-5">
                <h3 class="text-center">Categories</h3>
                <hr>
                <ul class="list-unstyled">
                    <li {% if not category %}class="border-bottom border-info px-3"
                        {% endif %}>
                        <a class="text-decoration-none text-dark" href="{% url 'shop:product_list' %}">All</a>
                    </li>
                    {% for c in category_list %}
                    <li {% if category.slug == c.slug %} class="border-bottom border-info px-3" {% endif %}>
                        <a class="text-dark text-decoration-none" href="{{ c.get_absolute_url }}">{{ c.name|title }}</a>
                    </li>
                    {% endfor %}
                </ul>
            </div>
        </div>
        <div class="col-lg mt-5">

            <div class="row row-cols-1 row-cols-md-3 g-4">
                {% for product in product_list %}
                <a class="text-decoration-none text-dark" href="{{product.get_absolute_url}}">
                <div class="col">
                  <div class="card shadow">
                    <div class="row g-0">
                        <div class="col-md-4">
                          <img 
                          {% if product.image %} 
                          src="{{product.image.url}}" 
                          {% else %} 
                          {% static 'img/no_image.png' %} 
                          {% endif %} 
                          class="img-fluid rounded-start" alt="{{product.title}}">
                        </div>
                        <div class="col-md-8">
                    <div class="card-body">
                      <p class="card-title">
                          
                        {{product.name|title}}
                        </p>
                      <p class="card-text">${{product.price}}</p>
                      <p class="card-text">{{product.detail}}</p>
                    </div>
                     </div>
                  </div>
                </div>
                </div>
            </a>

            {% endfor %}
              </div>
      
        </div>
</div>
</div>

{% endblock content %}